### ISSUE TITLE
Sponsors not visible - .sponsors-logo has a problem 

### ISSUE THREAD

**Issue by mariopce** [Mobilization/2015.mobilization.pl#1]
I notice that .sponsor-logo extends some css class and force to don't display content
I copied .sponsor-logo to .sponsor-logo2 and it started works. 
I tried fix this but I don't know how. 
Please help me 

``` css
::content #widget-box-ad-1, ::content #header-adverts, ::content .linkads, ::content #DartAd300x250, ::content .ad234, ::content .lr-ad, ::content .cmMediaRotatorAdSponsor, ::content #ad-inner, ::content .header-taxonomy-image-sponsor, ::content .rectangle-ad, ::content .ad-board, ::content .sl_admarker, ::content .adVplaceholder, ::content #ad_zone3, ::content #adv-fb-container, ::content #top_adv, ::content .widget_adsensem, ::content .ad-300x250-first, ::content .sponsor-logo, ::content #ad_0 {
display: none;
}
```

**Comment by marciniwanicki** [comment]
I guess you it might be caused by adblock plugin. Changing class name is a good way to hack it :+1:

**Comment by marciniwanicki** [comment]
Full list of filtered classes in AdBlock 2.35, .sponsor-logo included.

``` css
.pd-ads-mpu, .peg_ad, .pencil-ad, .pencil-ad-container, .pencil_ad, .performancingads_region, .pfimgAds, .pg-ad-block, .pgAdSection_Home_MasterSponsers, .photo-ad, .photoad, .photobox-adbox, .pics_detail_ad, .pics_footer_ad, .picto_ad, .pkgTemplateAdWrapper, .pla_ad, .placeholder-ad, .placeholderAd, .plainAd, .play-page-ads, .playAds1, .playAds2, .player-ads, .player-leaderboard-ad-wrapper, .player-under-ad, .playerAd, .player_ad2, .player_ad_box, .player_page_ad_box, .plistaList > .itemLinkPET, .plista_inimg_box, .plista_widget_belowArticleRelaunch_item[data-type="pet"], .pm-banner-ad, .pmad-in2, .pmg-sponsoredlinks, .pn-ad, .pn_dfpads, .pnp_ad, .poac_ads_text, .pod-ad, .pod-ad-300, .pod-ad-box, .podRelatedAdLinksWidget, .podSponsoredLink, .poll_sponsor_ad, .pop-up-ad, .popadtext, .popunder-adv, .popup-ad, .popupAd, .popupAdOuter, .popupAdWrapper, .popup_ad, .portalCenterContentAdBottom, .portalCenterContentAdMiddle, .portalCenterContentAdTop, .portal_searchresultssponsoredlist, .portalcontentad, .pos_advert, .post-adsense-bottom, .post-advert, .post-advertisement, .post-googlead, .post-load-ad, .post-nativeadcarousel, .postAd, .postWideAd, .post__ad, .post__body-ad-center, .post__inarticle-ad-template, .post_advert, .post_seperator_ad, .post_sponsor_unit, .post_sponsored, .postads, .postadsense, .postbit_ad_block, .postbit_adbit_register, .postbit_adcode, .postbody_ads, .poster-ad-asset-module, .poster_ad, .postfooterad, .postgroup-ads, .postgroup-ads-middle, .power_by_sponsor, .ppp_interior_ad, .pq-ad, .pr-ad-tower, .pr-widget, .pre-title-ad, .prebodyads, .premium-ad, .premium-ads, .premium-adv, .premiumInHouseAd, .premium_ad_container, .premiumad, .preview-ad, .pricead-border, .primary-ad, .primary-advertisment, .primary_sidebar_ad, .printAds, .pro_ad_adzone, .pro_ad_system_ad_container, .pro_ad_zone, .prod_grid_ad, .product-ads, .product-inlist-ad, .profile_ad_bottom, .profile_ad_top, .promo-ad, .promo-box--ad, .promo-box--leaderboard-ad, .promo-class-brand-getprice, .promoAds, .promoAdvertising, .promo_ad, .promo_border, .promoad, .promoboxAd, .promotionTextAd, .proof_ad, .ps-ad, .ps-ligatus_placeholder, .publiboxright300, .publication-ad, .publicidadSuperior, .publicidad_horizontal, .publicidade-dotted, .puff-ad, .puff-advertorials, .pull_top_ad, .pulse360ad, .pulsir-ad, .puppyAd, .purchad, .push--ad, .push-ad, .pushDownAd, .pushdownAd, .pw_wb_ad_300x250, .pwgAdWidget, .pxz-ad-widget, .pxz-taskbar-anchor, .qa_ad_left, .qm-ad, .qm-ad-content, .qm-ad-content-news, .quick-tz-ad, .quicklinks-ad, .quigo, .quigo-ad, .quigoAdCenter, .quigoAdRight, .quigoMod, .quigoads, .quotead, .qzvAdDiv, .r_ad, .r_ad_1, .r_ad_box, .r_adbx_top, .r_ads, .r_col_add, .rad_container, .raff_ad, .rail-article-sponsored, .rail_ad, .railad, .railadspace, .rbFooterSponsors, .rc_ad_300x100, .rc_ad_300x250, .rd_header_ads, .rdio-homepage-widget, .readerads, .readermodeAd, .realtor-ad, .rec_ad, .recent-post-widget-ad, .recentAds, .recent_ad_holder, .rect-ad, .rect-ad-1, .rect_ad, .rect_ad_module, .rect_advert, .rectad, .rectadv, .rectangle-ad, .rectangle-ad-container, .rectangle-embed-ad, .rectangleAd, .rectangleAdContainer, .rectanglead, .rectangleads, .redads_cont, .reedwan_adds300x250_widget, .referrerDetailAd, .refreshable_ad, .region-ads, .region-banner-ad, .region-dfp-ad-content-bottom, .region-dfp-ad-content-top, .region-dfp-ad-footer, .region-dfp-ad-header, .region-header-ad, .region-header-ads, .region-leader-ad-bottom, .region-leader-ad-top, .region-middle-ad, .region-regions-ad-top, .region-regions-ad-top-inner, .region-widget-ad-top-0, .regular_728_ad, .regularad, .reklam-block, .reklam2, .reklam728, .reklama-c, .reklama-vert, .reklama1, .reklame-right-col, .reklame-wrapper, .reklamka, .rel_ad_box, .related-ad, .related-ads, .related-al-ads, .related-al-content-w150-ads, .related-guide-adsense, .relatedAds, .relatedContentAd, .related_post_google_ad, .relatesearchad, .remads, .remnant_ad, .remove-ads, .removeAdsLink, .residentialads, .resourceImagetAd, .respAds, .responsive-ad, .result-ad, .result-sponsored, .resultAd, .result_ad, .result_item_ad-adsense, .resultad, .resultsAdsBlockCont, .results_sponsor_right, .rev_square_side_door, .review-ad, .reviewMidAdvertAlign, .review_ad1, .reviewpage_ad2, .reviews-box-ad, .rf_circ_ad_460x205, .rght300x250, .rgt-300x250-ad, .rgt-ad, .rgt_ad, .rhads, .rhc-ad-bottom, .rhs-ad, .rhs-ads-panel, .rhs-advert-container, .rhs-advert-link, .rhs-advert-title, .rhs_ad_title, .rhsad, .rhsadvert, .ribbon-ad-matte, .right-ad-300x250, .right-ad-block, .right-ad-holder, .right-ad2, .right-ads, .right-ads2, .right-adsense, .right-advert, .right-col-ad, .right-column-ad, .right-navAdBox, .right-rail-ad, .right-rail-ad-banner, .right-rail-broker-ads, .right-rail__ad, .right-rail__container--ad, .right-side-ad, .right-side-ads, .right-sidebar-box-ad, .right-sidebar-box-ads, .right-square-ad-blocks, .right-takeover-ad, .right-takeover-ad-sticky, .right-top-ad, .rightAD, .rightAdBox, .rightAdColumn, .rightAdContainer, .rightAd_bottom_fmt, .rightAd_top_fmt, .rightAds_ie_fix, .rightAdvert, .rightAdverts, .rightBoxAd, .rightBoxMidAds, .rightColAd, .rightColAdBox, .rightColumnAd, .rightColumnAdd, .rightColumnAdsTop, .rightColumnRectAd, .rightHeaderAd, .rightRailAd, .rightRailMiddleAd, .rightSecAds, .rightSideBarAd, .rightSideSponsor, .rightTopAdWrapper, .right_ad_160, .right_ad_box, .right_ad_box1, .right_ad_common_block, .right_ad_innercont, .right_ad_text, .right_ad_top, .right_ad_unit, .right_ads, .right_adsense_box_2, .right_adv, .right_advert, .right_advertise_cnt, .right_advertisement, .right_block_advert, .right_box_ad, .right_box_ad_rotating_container, .right_col_ad, .right_col_ad_300_250, .right_column_ads, .right_content_ad, .right_content_ad_16, .right_google_ads, .right_hand_advert_column, .right_image_ad, .right_long_ad, .right_outside_ads, .right_picAd, .right_side-partyad, .right_side_ads, .right_side_box_ad, .rightad250, .rightad_1, .rightad_2, .rightadbig, .rightadblock, .rightadbox1, .rightadd, .rightads, .rightadunit, .rightbigcolumn_ads, .rightbigcolumn_ads_nobackground, .rightbox_content_ads, .rightboxads, .rightcol-adbox, .rightcol-block-ads, .rightcol_boxad, .rightcol_div_openx2, .rightcoladvert, .rightcoltowerad, .rightmenu_ad, .rightnav_adsense, .rightpanelad, .rightrail-ad-block, .rightrail_ads, .rightsideAd, .ringtone-ad, .risingstar-ad, .risingstar-ad-inner, .riverSponsor, .rmx-ad, .rnav_ad, .rngtAd, .rockmelt-ad, .rockmeltAdWrapper, .rolloverad, .rot_ads, .rotating-ad, .rotating-ads, .rotatingAdvertisement, .rotatingadsection, .rotator_ad_overlay, .round_box_advert, .roundedCornersAd, .roundingrayboxads, .rowad, .rowgoogleads, .rr-300x250-ad, .rr-300x600-ad, .rr_ads, .rr_skyad, .rs_ad_bot, .rs_ad_top, .rside_adbox, .rtAdFtr, .rtSideHomeAd, .rt_ad, .rt_ad1_300x90, .rt_ad_300x250, .rt_ad_call, .rt_advert_name, .rt_el_advert, .rtd_ads_text, .rtmad, .rtmm_right_ad, .runner-ad, .s-ad, .s-ads, .s2k_ad, .sType-ad, .s_ad, .s_ad2, .s_ad_160x600, .s_ad_300x250, .s_ads, .s_ads_label, .s_sponsored_ads, .sa_AdAnnouncement, .sadvert, .sam-ad, .sam_ad, .savvyad_unit, .say-center-contentad, .sb-ad, .sb-ad-sq-bg, .sb-ad2, .sb-ad3, .sb-ads-here, .sbAd, .sbAdUnitContainer, .sbTopadWrapper, .sb_ad, .sb_ad_holder, .sb_adsN, .sb_adsNv2, .sb_adsW, .sb_adsWv2, .sc-ad, .sc_ad, .sc_iframe_ad, .scad, .scanAd, .scc_advert, .schedule_ad, .sci-ad-main, .sci-ad-sub, .scoopads, .scraper_ad_unit, .script-ad, .scroll-ads, .scrolling-ads, .search-ad, .search-advertisement, .search-results-ad, .search-sponsor, .search-sponsored, .searchAd, .searchAdTop, .searchCenterBottomAds, .searchCenterTopAds, .searchResultAd, .searchRightBottomAds, .searchRightMiddleAds, .searchSponsorItem, .searchSponsoredResultsBox, .searchSponsoredResultsList, .search_ad_box, .search_column_results_sponsored, .search_inline_web_ad, .search_results_ad, .search_results_sponsored_top, .sec-ad, .secondary-advertisment, .secondaryAdModule, .secondary_ad, .section-ad, .section-ad-related, .section-ad-wrapper, .section-ad2, .section-adbox-bottom, .section-adbox1, .section-ads, .section-adtag, .section-advert-banner, .section-aside-ad, .section-sponsor, .section_ad, .section_ad_left, .section_mpu_wrapper, .section_mpu_wrapper_wrapper, .selection-grid-advert, .selfServeAds, .seoTopAds, .sepContentAd, .series-ad, .serp_sponsored, .servedAdlabel, .servsponserLinks, .set_ad, .sfsp_adadvert, .sgAd, .shadvertisment, .shareToolsItemAd, .shift-ad, .shoppingGoogleAdSense, .shortads, .shortadvertisement, .showAdContainer, .showAd_No, .showAd_Yes, .showad_box, .showcaseAd, .showcasead, .si-adRgt, .sidbaread, .side-ad-120-bottom, .side-ad-120-middle, .side-ad-120-top, .side-ad-160-bottom, .side-ad-160-middle, .side-ad-160-top, .side-ad-300, .side-ad-300-bottom, .side-ad-300-middle, .side-ad-300-top, .side-ad-big, .side-ad-blocks, .side-ad-container, .side-ads, .side-ads-block, .side-ads-wide, .side-ads300, .side-bar-ad-position2, .side-sky-banner-160, .side-video-ads-wrapper, .sideAd, .sideAdTall, .sideAdWide, .sideBannerAdsLarge, .sideBannerAdsSmall, .sideBannerAdsXLarge, .sideBarAd, .sideBarCubeAd, .sideBlockAd, .sideBoxAd, .sideBoxM1ad, .sideBoxMiddleAd, .sideBySideAds, .sideToSideAd, .side_300_ad, .side_ad, .side_ad2, .side_ad300, .side_ad_1, .side_ad_2, .side_ad_3, .side_ad_box_mid, .side_ad_box_top, .side_ads, .side_adsense, .side_adv, .side_adv_01, .side_adv_left, .side_adv_right, .sidead, .sidead_150, .sidead_300, .sidead_300250_ht, .sidead_550125, .sideads, .sideads_l, .sideadsbox, .sideadtable, .sideadvert, .sidebar-350ad, .sidebar-ad, .sidebar-ad-300, .sidebar-ad-300x250-cont, .sidebar-ad-a, .sidebar-ad-b, .sidebar-ad-c, .sidebar-ad-cont, .sidebar-ad-container, .sidebar-ad-container-1, .sidebar-ad-container-2, .sidebar-ad-container-3, .sidebar-ad-rect, .sidebar-ad-slot, .sidebar-adbox, .sidebar-ads, .sidebar-advertisement, .sidebar-atf-ad-wrapper, .sidebar-big-ad, .sidebar-block-adsense, .sidebar-box-ad, .sidebar-box-ads, .sidebar-content-ad, .sidebar-header-ads, .sidebar-paid-ad-label, .sidebar-skyscraper-ad, .sidebar-sponsors, .sidebar-square-ad, .sidebar-text-ad, .sidebar-top-ad, .sidebar300adblock, .sidebarAd, .sidebarAdBlock, .sidebarAdNotice, .sidebarAdUnit, .sidebarAds300px, .sidebarAdvert, .sidebarCloseAd, .sidebarNewsletterAd, .sidebar_ADBOX, .sidebar_ad, .sidebar_ad_300, .sidebar_ad_300_250, .sidebar_ad_580, .sidebar_ad_container, .sidebar_ad_container_div, .sidebar_ad_holder, .sidebar_ad_leaderboard, .sidebar_ad_module, .sidebar_ads, .sidebar_ads-300x250, .sidebar_ads_336, .sidebar_ads_left, .sidebar_ads_right, .sidebar_ads_title, .sidebar_adsense, .sidebar_advert, .sidebar_advertising, .sidebar_box_ad, .sidebar_right_ad, .sidebar_skyscraper_ad, .sidebar_small_ad, .sidebar_sponsors, .sidebarad, .sidebarad160, .sidebarad_bottom, .sidebaradbox, .sidebaradcontent, .sidebarads, .sidebaradsense, .sidebarboxad, .sideheadnarrowad, .sideheadsponsorsad, .sidelist_ad, .sideskyad, .simple_ads_manager_block_widget, .simple_ads_manager_widget, .simple_ads_manager_zone_widget, .simple_adsense_widget, .simplead-container, .simpleads-item, .single-ad-anchor, .single-ad-wrap, .single-ads, .single-google-ad, .single-post-ad, .single-post-ads-750x90, .single-top-ad, .singleAdBox, .singleAdsContainer, .single_ad, .single_advert, .single_bottom_ad, .single_fm_ad_bottom, .single_top_ad, .singlead, .singleads, .singleadstopcstm2, .singlepageleftad, .singlepostad, .singlepostadsense, .singpagead, .site-ad-block, .site-ads, .site-footer__ad-area, .site-head-ads, .site-top-ad, .siteWideAd, .site_ad, .site_ad_120_600, .site_ad_300x250, .site_sponsers, .sitesponsor, .sitesprite_ads, .skin_ad_638, .skinad-l, .skinad-r, .sky-ad, .skyAd, .skyAdd, .skyAdvert, .skyAdvert2, .skyCraper_bannerLong, .skyCraper_bannerShort, .sky_ad_top, .sky_scraper_ad, .skyjobsadtext, .skyscraper-ad, .skyscraper_ad, .skyscraper_bannerAdHome, .skyscraper_banner_ad, .sl-art-ad-midflex, .sl-header-ad, .sl_admarker, .sleekadbubble, .slideAd, .slide_ad, .sliderad, .slideshow-ad, .slideshow-ad-wrapper, .slideshow-ads, .slideshow-advertisement-note, .slideshowAd, .slideshow_ad_300, .slideshow_ad_note, .slot_728_ad, .slot_integrated_ad, .slpBigSlimAdUnit, .slpSquareAdUnit, .sm-ad, .smAdText_r, .sm_ad, .small-ad-header, .small-ads, .smallAdContainer, .smallAdvertisments, .smallSkyAd1, .smallSkyAd2, .small_ad_bg, .small_ads, .smallad, .smallad-left, .smalladblock, .smalladscontainer, .smalladword, .smallbutton-adverts, .smallsideadpane, .smallsponsorad, .smart_ads_bom_title, .sml-item-ad, .sn-ad-300x250, .snarcy-ad, .snoadnetwork, .social-ad, .softronics-ad, .southad, .sp-ad, .spLinks, .spaceAdds, .specialAd175x90, .specialAdsContent, .specialAdsLabel, .specialAdsLink, .specialAdvertising, .special_ad_section, .specials_ads, .speedyads, .sphereAdContainer, .spl-ads, .spl_ad, .spl_ad2, .spl_ad_plus, .splitAd, .splitAdResultsPane, .splitter_ad, .splitter_ad_holder, .spn_links_box, .spnsrAdvtBlk, .spnsrCntnr, .spon-links, .spon125, .spon_link, .sponadbox, .sponlinkbox, .spons-link, .spons-wrap, .sponsBox, .sponsLinks, .sponsWrap, .spons_link_header, .spons_links, .sponser-link, .sponserIABAdBottom, .sponserLink, .sponsersads, .sponsertop, .sponslink, .sponsor-728, .sponsor-ad, .sponsor-ad-wrapper, .sponsor-area, .sponsor-block, .sponsor-bottom, .sponsor-btns, .sponsor-inner, .sponsor-left, .sponsor-link, .sponsor-links, .sponsor-logo, .sponsor-module-target, .sponsor-post, .sponsor-promo, .sponsor-right, .sponsor-services, .sponsor-spot, .sponsor-text, .sponsor-text-container, .sponsor120x600, .sponsor728x90, .sponsorArea, .sponsorBannerWrapper, .sponsorBlock, .sponsorBox, .sponsorBox_right_rdr, .sponsorLabel, .sponsorLink, .sponsorLinks, .sponsorMaskhead, .sponsorPanel, .sponsorPost, .sponsorPostWrap, .sponsorPuffsHomepage, .sponsorStrip, .sponsorText, .sponsorTitle, .sponsorTxt, .sponsor_ad, .sponsor_ad1, .sponsor_ad2, .sponsor_ad3, .sponsor_ad_area, .sponsor_advert_link, .sponsor_area, .sponsor_bar, .sponsor_block, .sponsor_button_ad, .sponsor_columns, .sponsor_div, .sponsor_div_title, .sponsor_footer, .sponsor_image, .sponsor_label, .sponsor_line, .sponsor_links, .sponsor_logo, .sponsor_placement, .sponsor_units, .sponsorad, .sponsoradlabel, .sponsorads, .sponsoradtitle, .sponsored-ad, .sponsored-ad-label, .sponsored-ad-ob, .sponsored-ads, .sponsored-b, .sponsored-chunk, .sponsored-container-bottom, .sponsored-default, .sponsored-display-ad, .sponsored-editorial, .sponsored-features, .sponsored-header, .sponsored-headshop, .sponsored-link, .sponsored-links, .sponsored-links-alt-b, .sponsored-links-col, .sponsored-links-holder, .sponsored-links-right, .sponsored-links-tbl, .sponsored-offers-box, .sponsored-post, .sponsored-post_ad, .sponsored-result, .sponsored-result-row-2, .sponsored-results, .sponsored-right, .sponsored-right-border, .sponsored-rule, .sponsored-slot, .sponsored-tag, .sponsored-text, .sponsored-title, .sponsored-top, .sponsoredAd, .sponsoredAdLine, .sponsoredAds, .sponsoredBar, .sponsoredBottom, .sponsoredBox, .sponsoredEntry, .sponsoredFeature, .sponsoredInfo, .sponsoredInner, .sponsoredLabel, .sponsoredLeft, .sponsoredLink, .sponsoredLinks2, .sponsoredLinksBox, .sponsoredLinksGadget, .sponsoredLinksHead, .sponsoredLinksHeader, .sponsoredName, .sponsoredProduct, .sponsoredResults, .sponsoredSearch, .sponsoredShowcasePanel, .sponsoredSideInner, .sponsoredStats, .sponsoredTop, .sponsored_ad, .sponsored_ads, .sponsored_box, .sponsored_box_search, .sponsored_by, .sponsored_content, .sponsored_glinks, .sponsored_link, .sponsored_links, .sponsored_links2, .sponsored_links_box, .sponsored_links_container, .sponsored_links_section, .sponsored_links_title_container, .sponsored_links_title_container_top, .sponsored_links_top, .sponsored_result, .sponsored_results, .sponsored_ss, .sponsored_text, .sponsored_well, .sponsoredby, .sponsoredibbox, .sponsoredlink, .sponsoredlinkHed, .sponsoredlinks, .sponsoredlinks-article, .sponsoredlinkscontainer, .sponsoredresults, .sponsoredtabl, .sponsoredtextlink_container_ovt, .sponsorheader, .sponsoring_link, .sponsoringbanner, .sponsorlink2, .sponsormsg, .sponsors-box, .sponsors-footer, .sponsors-module, .sponsorsBanners, .sponsors_300x250, .sponsors_box_container, .sponsors_fieldset, .sponsors_links, .sponsors_spacer, .sponsorsbig, .sponsorship-box, .sponsorship-container, .sponsorshipContainer, .sponsorship_ad, .sponsorshipbox, .sponsorwrapper, .sport-mpu-box, .spot-ad, .spotlight-ad, .spotlight-ad-left, .spotlightAd, .sprite-ad_label_vert, .sqAd2, .sq_ad, .square-ad, .square-ad--latest-video, .square-ad--neg-margin, .square-ad-1, .square-ad-container, .square-advt, .square-sidebar-ad, .square-sponsorship, .squareAd, .squareAdWrap, .squareAdd {
  display: none;
  orphans: 4321;
}
```
